[project]
name = "pbc"
version = "3.0.0"
description = "Protein (language model) Benchmarking Collection - PBC"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "biotite>=1.7.1",
    "biocentral>=2.0.0", # @ git+https://github.com/biocentral/biocentral.git@refactor/monorepo#subdirectory=biocentral_python",
    "scikit-learn>=1.9.0",
]

[tool.uv.sources]
biocentral = { path = "../../IdeaProjects/biocentral/biocentral_python", editable = true}